[parity]
chain = "/musereum-testnet-genesis.json"
[network]
port = 30300
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
[websockets]
port = 8450
[mining]
engine_signer = "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1"
reseal_on_txs = "none"
